GLOBAL ELECTRONIC RETAILS ANALYSIS SNOWFLAKE 

-- Database 
USE DATABASE GLB_ELEC_RETS;

-- Schema 
CREATE SCHEMA GER2;
USE SCHEMA GER2;

-- Customers Table 
DESC TABLE CUSTOMERS;
SELECT * FROM CUSTOMERS;

-- Exchange_Rates Table 
DESC TABLE EXCHANGE_RATES;
SELECT * FROM EXCHANGE_RATES;

-- Products Table 
DESC TABLE PRODUCTS;
SELECT * FROM PRODUCTS;

-- Sales Table
DESC TABLE SALES;


SELECT * FROM SALES;

-- Stores Table
DESC TABLE STORES;
SELECT * FROM STORES;


-- SALES Table & EXCHANGE Table 

-- Exchange_Rates Unique Key 
ALTER TABLE EXCHANGE_RATES ADD COLUMN DATE_CURRENCY STRING;
UPDATE EXCHANGE_RATES SET DATE_CURRENCY =  CONCAT(TO_VARCHAR("DATE", 'YYYYMMDD'), '-', "CURRENCY");

-- Sales Unique Key (Exchange_Rates Table)
ALTER TABLE SALES ADD COLUMN ORDERDATE_CURRENCY STRING;
UPDATE SALES SET ORDERDATE_CURRENCY =  CONCAT(TO_VARCHAR("ORDER_DATE", 'YYYYMMDD'), '-', "CURRENCY_CODE");

-- Sales Unique Key (Sales Dimension Table)
ALTER TABLE SALES ADD COLUMN ORDERNUMBER_LINEITEM STRING;
UPDATE SALES SET ORDERNUMBER_LINEITEM = MD5(CONCAT("ORDER_NUMBER" || '-' || "LINE_ITEM"));

-- Creating Fact Table 
CREATE OR REPLACE TABLE GLB_ELEC_RETS.GER2.FACT_TABLE AS 
( SELECT A."CUSTOMERKEY", A."STOREKEY", A."PRODUCTKEY", A."QUANTITY", B."DATE_CURRENCY" AS EXCHANGEDIMKEY, A."ORDERNUMBER_LINEITEM" FROM GLB_ELEC_RETS.GER2.SALES A 
JOIN GLB_ELEC_RETS.GER2.EXCHANGE_RATES B ON A."ORDERDATE_CURRENCY" = B."DATE_CURRENCY");

SELECT * FROM GLB_ELEC_RETS.GER2.FACT_TABLE;

-- Create Sales Dimension Table 
CREATE OR REPLACE TABLE GLB_ELEC_RETS.GER2.SALES_DIM AS 
( SELECT A."ORDER_NUMBER", A."LINE_ITEM", A."ORDER_DATE", A."ORDERNUMBER_LINEITEM" FROM GLB_ELEC_RETS.GER2.SALES A );

